const locations = [
    {
      region: "Greater Accra",
      towns: [
        { name: "Tema", delivery_fee: 45 },
        { name: "Kasoa", delivery_fee: 45 },
        { name: "Ashaiman", delivery_fee: 45 },
        { name: "Dome", delivery_fee: 35 },
        { name: "Madina", delivery_fee: 45 },
        { name: "Adenta", delivery_fee: 45 },
        { name: "Gbawe", delivery_fee: 40 },
        { name: "Nungua", delivery_fee: 40 },
        { name: "Teshie", delivery_fee: 40 },
        { name: "Nsakina", delivery_fee: 50 },
        { name: "Amasaman", delivery_fee: 45 },
        { name: "Ofankor", delivery_fee: 40 },
        { name: "Kwabenya", delivery_fee: 40 },
        { name: "Achimota", delivery_fee: 35 },
        { name: "Ablekuma", delivery_fee: 45 },
        { name: "Dansoman", delivery_fee: 40 },
        { name: "Sakumono", delivery_fee: 45 },
        { name: "Lashibi", delivery_fee: 45 },
        { name: "Oyibi", delivery_fee: 40 },
        { name: "Kokrobite", delivery_fee: 45 },
        { name: "Bortianor", delivery_fee: 45 },
        { name: "Abokobi", delivery_fee: 40 },
        { name: "Aburi", delivery_fee: 0 },
        { name: "Somanya", delivery_fee: 0 },
        { name: "Dodowa", delivery_fee: 0 },
        { name: "Prampram", delivery_fee: 0 },
        { name: "Kpone", delivery_fee: 45 },
        { name: "Shai Hills", delivery_fee: 0 },
        { name: "Ada Foah", delivery_fee: 0 },
        { name: "Dawhenya", delivery_fee: 0 },
        { name: "Afienya", delivery_fee: 45 },
        { name: "Dunkonah", delivery_fee: 0 },
        { name: "Apollonia", delivery_fee: 0 },
        { name: "Oshiyie", delivery_fee: 0 },
        { name: "Michel Camp", delivery_fee: 40 },
        { name: "Asutuare", delivery_fee: 0 },
        { name: "Akuse", delivery_fee: 0 },
        { name: "Kpoguno", delivery_fee: 0 },
        { name: "Obom", delivery_fee: 0 },
        { name: "Mamahuma", delivery_fee: 0 },
        { name: "Adabraka", delivery_fee: 30 },
        { name: "Cantoments", delivery_fee: 30 },
        { name: "Ridge", delivery_fee: 30 },
        { name: "Lapaz", delivery_fee: 35 },
        { name: "Osu", delivery_fee: 30 },
        { name: "Abeka", delivery_fee: 35 },
        { name: "New Town Kotobabi", delivery_fee: 30 },
        { name: "Dwowulu", delivery_fee: 35 },
        { name: "Agbobloshie", delivery_fee: 35 },
        { name: "East Legon", delivery_fee: 40 }
      ]
    },
    {
        region: "Ashanti",
        towns: [
          { name: "Kumasi", delivery_fee: 0 },
          { name: "Obuasi", delivery_fee: 0 },
          { name: "Konongo", delivery_fee: 0 },
          { name: "Mampong", delivery_fee: 0 },
          { name: "Ejisu", delivery_fee: 0 },
          { name: "Bekwai", delivery_fee: 0 },
          { name: "Effiduasi", delivery_fee: 0 },
          { name: "Juaben", delivery_fee: 0 },
          { name: "Asante Mampong", delivery_fee: 0 },
          { name: "Asokwa", delivery_fee: 30 },
          { name: "Oforikrom", delivery_fee: 30 },
          { name: "Bantama", delivery_fee: 30 },
          { name: "Tafo", delivery_fee: 30 },
          { name: "Asawasi", delivery_fee: 30 },
          { name: "Ahinsan", delivery_fee: 35 },
          { name: "Manhyia", delivery_fee: 30 },
          { name: "Suame", delivery_fee: 30 },
          { name: "Kwadaso", delivery_fee: 35 },
          { name: "Asokore Mampong", delivery_fee: 35 },
          { name: "Krofrom", delivery_fee: 30 },
          { name: "Ayigya", delivery_fee: 35 },
          { name: "Old Tafo", delivery_fee: 30 },
          { name: "Ahwiaa", delivery_fee: 35 },
          { name: "Agona", delivery_fee: 0 },
          { name: "Boadi", delivery_fee: 35 },
          { name: "Adansi", delivery_fee: 0 },
          { name: "Fomena", delivery_fee: 0 },
          { name: "Tepa", delivery_fee: 0 },
          { name: "Jacobu", delivery_fee: 0 },
          { name: "Asankare", delivery_fee: 0 },
          { name: "Akrokeri", delivery_fee: 0 },
          { name: "Agogo", delivery_fee: 0 },
          { name: "Konongo Odumasi", delivery_fee: 0 },
          { name: "Mamponteng", delivery_fee: 40 },
          { name: "Atimatim", delivery_fee: 40 },
          { name: "Pankrono", delivery_fee: 35 },
          { name: "Buokrom Estates", delivery_fee: 30 },
          { name: "Pankrono Estates", delivery_fee: 30 },
          { name: "Akrokerri", delivery_fee: 0 },
          { name: "Nyinahin", delivery_fee: 0 },
          { name: "Sepe", delivery_fee: 30 },
          { name: "Offinso", delivery_fee: 0 },
          { name: "Maakro", delivery_fee: 30 },
          { name: "Kotei", delivery_fee: 35 },
          { name: "Ayeduase", delivery_fee: 35 },
          { name: "Kenyase", delivery_fee: 35 },
          { name: "Ahenkro", delivery_fee: 0 },
          { name: "Akomadan Afrancho", delivery_fee: 0 },
          { name: "Kodie", delivery_fee: 0 },
          { name: "Kronom Afrancho", delivery_fee: 35 },
          { name: "Meduma", delivery_fee: 35 },
          { name: "Barekese", delivery_fee: 0 },
          { name: "Edwenase", delivery_fee: 0 },
          { name: "Brofoyedru", delivery_fee: 0 },
          { name: "Mampongten", delivery_fee: 0 },
          { name: "Nsuta", delivery_fee: 0 },
          { name: "Kwamo", delivery_fee: 0 },
          { name: "Asuokyene", delivery_fee: 0 },
          { name: "Ananekrom", delivery_fee: 0 },
          { name: "Aputuogya", delivery_fee: 0 },
          { name: "Asaam", delivery_fee: 0 },
          { name: "Asaatey", delivery_fee: 0 },
          { name: "Asempaneye", delivery_fee: 0 },
          { name: "Asuadee", delivery_fee: 0 },
          { name: "Asuoho", delivery_fee: 0 },
          { name: "Asuogya", delivery_fee: 0 },
          { name: "Atasamanso", delivery_fee: 0 },
          { name: "Atonsu", delivery_fee: 0 },
          { name: "Atwima Agogo", delivery_fee: 0 },
          { name: "Atwima Akyempim", delivery_fee: 0 },
          { name: "Atwima Apraman", delivery_fee: 0 },
          { name: "Atwima Atweban", delivery_fee: 0 },
          { name: "Atwima Dida", delivery_fee: 0 },
          { name: "Atwima Bonsu", delivery_fee: 0 },
          { name: "Atwima Dunkwa", delivery_fee: 0 },
          { name: "Atwima Kankana", delivery_fee: 0 },
          { name: "Atwima Koforidua", delivery_fee: 0 },
          { name: "Atwima Mansukrom", delivery_fee: 0 },
          { name: "Atwima Nkoransa", delivery_fee: 0 },
          { name: "Atwima Nkorbra", delivery_fee: 0 },
          { name: "Atwima Nkwanta", delivery_fee: 0 },
          { name: "Atwima Odumasi", delivery_fee: 0 },
          { name: "Atwima Oforikrom", delivery_fee: 0 },
          { name: "Atwima Tafrakwa", delivery_fee: 0 },
          { name: "Atwima Yayaaso", delivery_fee: 0 },
          { name: "Bonkron", delivery_fee: 0 },
          { name: "Bontodiase", delivery_fee: 0 },
          { name: "Bowiesakrom", delivery_fee: 0 },
          { name: "Dampai", delivery_fee: 0 },
          { name: "Diawuo", delivery_fee: 0 },
          { name: "Domenya", delivery_fee: 0 },
          { name: "Dukuben", delivery_fee: 0 },
          { name: "Esireso", delivery_fee: 0 },
          { name: "Fakopa", delivery_fee: 0 },
          { name: "Fenchi", delivery_fee: 0 },
          { name: "Foase", delivery_fee: 0 },
          { name: "Fumso", delivery_fee: 0 },
          { name: "Hia", delivery_fee: 0 },
          { name: "Hwidiem", delivery_fee: 0 },
          { name: "Jacobu", delivery_fee: 0 },
          { name: "Kaben", delivery_fee: 0 },
          { name: "Kankawura", delivery_fee: 0 },
          { name: "Kenyasi", delivery_fee: 0 },
          { name: "Kotey", delivery_fee: 0 },
          { name: "Kumedi", delivery_fee: 0 },
          { name: "Kwadwoakrom", delivery_fee: 0 },
          { name: "Kwaaman", delivery_fee: 0 },
          { name: "Libona", delivery_fee: 0 },
          { name: "Mampongteng", delivery_fee: 0 },
          { name: "Mankrong", delivery_fee: 0 },
          { name: "Nyamebekyere", delivery_fee: 0 },
          { name: "Obogu", delivery_fee: 0 },
          { name: "Ofari", delivery_fee: 0 },
          { name: "Ohwim", delivery_fee: 0 },
          { name: "Potromu", delivery_fee: 0 },
          { name: "Yaati", delivery_fee: 0 },
          { name: "Yawhima", delivery_fee: 0 },
          { name: "Yawyawkrom", delivery_fee: 0 },
          { name: "Yenya", delivery_fee: 0 }
        ]
      },
      
    {
      region: "Eastern",
      towns: [
        "Koforidua", "Nsawam", "Somanya", "Akwatia", "Kade", "Asamankese", "Suhum", "Kyebi", "Apedwa", "Atimpoku",
        "Akim Oda", "Akwamufie", "Akim Swedru", "Achiase", "Ayirebi", "Kukurantumi", "Coaltar", "Aburi", "Apirede",
        "Boti Falls", "Abenase", "Ahankrasu", "Akwamu", "Aseseeso", "Asuogyaman", "Ayensuano", "Bewunaba", "Boadua",
        "Dawa", "Dedeso", "Efidwase", "Fawomang", "Kpedze", "Mampong Nkwanta", "Nkawkaw", "Odumasi", "Otwereso",
        "Tutu Akuapem", "Abomosu", "Aburi Akuapem", "Adukrom", "Akwamu Adawso", "Akuse", "Akyem Akropong",
        "Akyem Asuokofi", "Akyem Awisa", "Akyem Osino", "Akyem Tafo", "Amanokrom", "Asamankor", "Bunso", "Dodowa",
        "Kibi", "Abengonya", "Abetifi", "Abompe", "Abrɛsɛ", "Abrewankor", "Abrɛwatɔr", "Achiaman", "Adawso",
        "Adjeikrom", "Aduamoa", "Afefikrom", "Afienya", "Afram Plains", "Agomeda", "Agorowɔ", "Agɔna",
        "Akpɛtɛshie", "Akrɔbɔngo", "Akwamu Adɔkɔ", "Akwamu Awɔnsaw", "Akwamu Tɔdzisu", "Akwamudɔbɔ", "Akwasiho",
        "Akyɛm Abuakwa", "Akyɛm Asenɔ", "Akyɛm Awɛna", "Akyɛm Batɔr", "Akyɛm Bomfa", "Akyɛm Hɛman", "Akyɛm Maase",
        "Akyɛmfɔr", "Amanforɔ", "Amuana Prasu", "Anuɔmah", "Apapam", "Apinamang", "Asamankɛse", "Asamankɔm",
        "Asuɔkɔr", "Atɔa", "Ayɛnkɔkɔr", "Ayɛnsudu", "Ayɛnsu Nkwanta", "Ayɛnsu Obutɔr", "Bawjiasi", "Bɛgorɔ",
        "Bɛkwɛ", "Dawu", "Diawuo", "Dokuata", "Domeabra", "Fawomanye", "Gbɛtsile", "Gbɔngɔr", "Huhunya", "Ismalia",
        "Jejeti", "Kɔbɔ", "Kɔfɔr Akwamu", "Kɔfɔr Akwapim", "Kɔkɔɔ", "Kɔkrɔbɔ", "Kɔkwaatwɔ", "Kwaobɛnyan",
        "Kwamu Tafo", "Kwanyako", "Kyɛkytɔn", "Mampɔŋ Nkatiɛ", "Mampɔŋ Nkwanta", "Mfɔŋkrɔnor", "Muoho", "Nankɔnɔr",
        "Nankɔwa", "Nkurankuran", "Nkwankɔ", "Nsɔngɔr", "Ntoɔnakɔr"
      ].map(town => ({ name: town, delivery_fee: 0 }))
    },
    {
      region: "Ahafo",
      towns: [
        "Duayaw Nkwanta",
        "Bechem",
        "Goaso",
        "Kukuom",
        "Acherensua",
        "Kenyasi",
        "Bomaa",
        "Techimantia",
        "Mim",
        "Hwidiem",
        "Sankore"
      ].map(town => ({ name: town, delivery_fee: 0 }))
    },
    {
        region: "Bono",
        towns: [
          { name: "Sunyani", delivery_fee: 0 },
          { name: "Wenchi", delivery_fee: 0 },
          { name: "Berekum", delivery_fee: 0 },
          { name: "Dormaa Ahenkro", delivery_fee: 0 },
          { name: "Sampa", delivery_fee: 0 },
          { name: "Fiapre", delivery_fee: 0 },
          { name: "Derma", delivery_fee: 0 },
          { name: "Duadwenem", delivery_fee: 0 },
          { name: "Drobo", delivery_fee: 0 },
          { name: "Banda Ahenkro", delivery_fee: 0 },
          { name: "Asemfro", delivery_fee: 0 },
          { name: "Tromo", delivery_fee: 0 },
          { name: "Tanoso", delivery_fee: 0 },
          { name: "Nsuatre", delivery_fee: 0 },
          { name: "Awua Domase", delivery_fee: 0 },
          { name: "Akokrom", delivery_fee: 0 },
          { name: "Yeji", delivery_fee: 0 },
          { name: "Amoma", delivery_fee: 0 },
          { name: "Atronie", delivery_fee: 0 },
          { name: "Bakoniaba", delivery_fee: 0 },
          { name: "Baakofri", delivery_fee: 0 },
          { name: "Brahoho", delivery_fee: 0 },
          { name: "Subinso", delivery_fee: 0 },
          { name: "Dwenem", delivery_fee: 0 },
          { name: "Awuakwa", delivery_fee: 0 },
          { name: "Adumakrom", delivery_fee: 0 },
          { name: "Akrodie", delivery_fee: 0 },
          { name: "Bono Manso", delivery_fee: 0 },
          { name: "Brekukrom", delivery_fee: 0 },
          { name: "Chiraa", delivery_fee: 0 },
          { name: "Dadiesoaba", delivery_fee: 0 },
          { name: "Domefiri", delivery_fee: 0 },
          { name: "Dwereboh", delivery_fee: 0 },
          { name: "Fonikrom", delivery_fee: 0 },
          { name: "Krabonso", delivery_fee: 0 },
          { name: "Kwatire", delivery_fee: 0 },
          { name: "Mehame", delivery_fee: 0 },
          { name: "Ntunsko", delivery_fee: 0 },
          { name: "Ofoase", delivery_fee: 0 },
          { name: "Oforikrom", delivery_fee: 0 },
          { name: "Okumaning", delivery_fee: 0 },
          { name: "Sang", delivery_fee: 0 },
          { name: "Seikwa", delivery_fee: 0 },
          { name: "Seneso", delivery_fee: 0 },
          { name: "Sukurunumu", delivery_fee: 0 },
          { name: "Tainso", delivery_fee: 0 },
          { name: "Yabraso", delivery_fee: 0 },
          { name: "Yawhima", delivery_fee: 0 },
          { name: "Yawmatwa", delivery_fee: 0 },
          { name: "Yefri", delivery_fee: 0 }
        ]
      },
      {
        region: "Bono East",
        towns: [
          { name: "Techiman", delivery_fee: 0 },
          { name: "Atebubu", delivery_fee: 0 },
          { name: "Kintampo", delivery_fee: 0 },
          { name: "Nkoranza", delivery_fee: 0 },
          { name: "Yeji", delivery_fee: 0 },
          { name: "Prang", delivery_fee: 0 },
          { name: "Kintampo North", delivery_fee: 0 },
          { name: "Jema", delivery_fee: 0 },
          { name: "Kajaji", delivery_fee: 0 },
          { name: "Krabonso", delivery_fee: 0 },
          { name: "Atuabeng", delivery_fee: 0 },
          { name: "Awisam", delivery_fee: 0 },
          { name: "Babatokuma", delivery_fee: 0 },
          { name: "Badu", delivery_fee: 0 },
          { name: "Baten", delivery_fee: 0 },
          { name: "Branam", delivery_fee: 0 },
          { name: "Busunya", delivery_fee: 0 },
          { name: "Dwenem", delivery_fee: 0 },
          { name: "Gyarkokrom", delivery_fee: 0 },
          { name: "Kaekye", delivery_fee: 0 },
          { name: "Kanyasi", delivery_fee: 0 },
          { name: "Kokrua", delivery_fee: 0 },
          { name: "Kyira", delivery_fee: 0 },
          { name: "Mansam", delivery_fee: 0 },
          { name: "Mansie", delivery_fee: 0 },
          { name: "Nante", delivery_fee: 0 },
          { name: "Nkokua", delivery_fee: 0 },
          { name: "Nkwantanan", delivery_fee: 0 },
          { name: "Nsuntra", delivery_fee: 0 },
          { name: "Ntrambasere", delivery_fee: 0 },
          { name: "Ofoase", delivery_fee: 0 },
          { name: "Oforikrom", delivery_fee: 0 },
          { name: "Okumaning", delivery_fee: 0 },
          { name: "Pepiatinankor", delivery_fee: 0 },
          { name: "Seikwa", delivery_fee: 0 },
          { name: "Sokwan", delivery_fee: 0 },
          { name: "Tanom", delivery_fee: 0 },
          { name: "Techiman North", delivery_fee: 0 },
          { name: "Tuobodom", delivery_fee: 0 }
        ]
      }
      
      
  ];
  
  export default locations;
  